# Generated by Django 4.2.7 on 2023-11-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_passportinfo_alter_author_options_remove_author_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passportinfo',
            name='age',
        ),
    ]
