# Generated by Django 4.2.7 on 2023-11-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_passportinfo_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportinfo',
            name='age',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Yoshi'),
        ),
        migrations.AddField(
            model_name='passportinfo',
            name='firstname',
            field=models.CharField(default='Nurbek', max_length=255),
        ),
        migrations.AddField(
            model_name='passportinfo',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
